### ISSUE TITLE
Mujoco as an optional dependency?

### ISSUE THREAD

**Issue by uduse** [rail-berkeley/d4rl#106]
Right now, it seems it's impossible to use a part of this project (e.g., Maze) without installing Mujoco. Can we make Mujoco an optional dependency instead?

**Comment by kayburns** [comment]
You can try cloning the repository, removing mujoco_py from the `install_requires` list in `setup.py` and installing with your change by running `pip install -e .` within the top level `d4rl` folder.

**Comment by uduse** [comment]
DeepMind just solved this problem for me by making Mujoco public :)
