### ISSUE TITLE
I am using gym 0.18.0 but still there is no `get_dataset()`

### ISSUE THREAD

**Issue by HYDesmondLiu** [rail-berkeley/d4rl#117]
I am using gym 0.18.0 but still there is no `get_dataset()`

_Originally posted by @HYDesmondLiu in https://github.com/rail-berkeley/d4rl/issues/87#issuecomment-898050781_

**Comment by xtwentian3** [comment]
Are you sure the d4RL has been installed successfully?

**Comment by HYDesmondLiu** [comment]
I have already solved this.
