### ISSUE TITLE
Visualization script has no goal

### ISSUE THREAD

**Issue by AbhinavGopal** [rail-berkeley/d4rl#138]
Hi,
Thanks for the release of these environments that help significantly with different experimental setups. I am currently trying to use the visualization script, and I notice that the goal is not being displayed in the goal location (the red ball, for example, in the maze envs). Is there a fix to this?

**Comment by AbhinavGopal** [comment]
Update: This can be done by calling set_target()

**Comment by RadwaElaraby** [comment]
Hello, 

Did it really work for you? 

I am trying to play the trajectories but the target is out of the maze?

goals = dataset['infos/goal']

for t in range(100);
    env.set_state(qpos[t], qvel[t])
    env.set_target(goals[t])
    env.render()

Any help is appreciated.

**Comment by RadwaElaraby** [comment]
okay, I have to call step() even for visualization.
