### ISSUE TITLE
gym.error.NameNotFound: Environment maze2d-umaze doesn't exist.

### ISSUE THREAD

**Issue by Chulabhaya** [rail-berkeley/d4rl#163]
Hello all. I am attempting to run the test script given in the readme of the repo with the simple Maze2D environment, but when attempting to run it I receive the following error: 

`gym.error.NameNotFound: Environment maze2d-umaze doesn't exist.`

Any ideas what I'm doing wrong?

**Comment by rdgy2017** [comment]
I got the  same problem. Do you have any solution, now?
