### ISSUE TITLE
Unable to run antmaze_sac.py

### ISSUE THREAD

**Issue by s-gupta** [rail-berkeley/d4rl#21]
Similar to #9, I believe appropriate version of rlkit is also needed to run antmaze_sac.py. Any estimate when the appropriate version of rlkit can be made available? 

In particular, current code crashes at MdpPathCollector with the error __init__() got an unexpected keyword argument 'sparse_reward'

**Comment by aviralkumar2907** [comment]
Thank you for pointing this out. We have added a script compatible with rlkit: https://github.com/rail-berkeley/d4rl/blob/master/scripts/antmaze_sac_rlkit.py 

This should work with rlkit. Version differences in gym may give rise to an assertion error, which is fixable using instructions at the top of the launcher script.
