### ISSUE TITLE
env.seed doesn't seem to work

### ISSUE THREAD

**Issue by nuria95** [rail-berkeley/d4rl#23]
env.seed(seed=x) doesn't seem to work.
After running previous command and doing env.reset(), I get different states every time.
It would be nice to get reproducible states to compare algorithms during evaluation

**Comment by justinjfu** [comment]
Which environment(s) is this not working for?

**Comment by nuria95** [comment]
For sure not working for Half-cheetah.
It works for the mazes2d environments.
Haven't checked for the others.
Thanks for your quick reply

**Comment by justinjfu** [comment]
This should be fixed!
