### ISSUE TITLE
Why MuJoCo instead of pyBullet?

### ISSUE THREAD

**Issue by ugurkanates** [rail-berkeley/d4rl#28]
No offense but just wondered wouldn't be more great using bullet3&pyBullet as baseline for this project since it's open source and better community support in general

**Comment by takuseno** [comment]
@ugurkanates Hi! I'm not sure if you're still interested in pybullet version. But, I've released new datasets collected in pybullet environments! 
https://github.com/takuseno/d4rl-pybullet

If it looks good to you, I'd be happy:)

**Comment by ugurkanates** [comment]
Thats great to know
