### ISSUE TITLE
Missing next observation in dataset.

### ISSUE THREAD

**Issue by RchalYang** [rail-berkeley/d4rl#31]
Hi! I'm recently exploring this dataset to study offline rl.

But i'm wondering why this dataset do not contain the information about next_observation in transitin? Is this on purpose or just a mistake?

Here is what i got:

\>\>\> env = gym.make("maze2d-large-v1")

\>\>\> dataset = env.env.get_dataset()

Downloading dataset: http://rail.eecs.berkeley.edu/datasets/offline_rl/maze2d/maze2d-large-sparse-v1.hdf5 to xxxxxxxxxxxxxxxxxxxxx

\>\>\> [dataset.keys()](url)

dict_keys([\'actions\', \'infos/goal\', \'infos/qpos\', \'infos/qvel\', \'observations\', \'rewards\', 'terminals'])`

**Comment by justinjfu** [comment]
We excluded next_observations to reduce the size of the files. The datasets should generally consist of entire trajectories (from start to terminal state) appended one after another, so you can extract the next_observation by looking at the next item in the sequence.

**Comment by RchalYang** [comment]
Thanks for the clarification. But maybe it's better to note it in the readme or somewhere else
