### ISSUE TITLE
BEAR Benchmark

### ISSUE THREAD

**Issue by nkleber1** [rail-berkeley/d4rl#33]
Hi Everyone

I am interested in benchmarking **BEAR**, but I cannot execute the corresponding script (**antmaze_bear.py**). I get the error message _"No module named 'rlkit.torch.sac.bear'"_. Unfortunately I cannot find a module corresponding to **BEAR** anywhere else in the **rlkit**. Can anyone tell me where I can find this code or share their code with me? 

Best regards
Nils

**Comment by aviralkumar2907** [comment]
Hi Nils,

All algorithms are now present in the d4rl_evaluations repo: https://github.com/rail-berkeley/d4rl_evaluations
