### ISSUE TITLE
Maze env: out-of-grid goal location?

### ISSUE THREAD

**Issue by wookayin** [rail-berkeley/d4rl#37]
I cannot have goal locations (shown as red dot) contained within the maze. Is this a bug of the environment?

![image](https://user-images.githubusercontent.com/1009873/87671296-1c4e9300-c73f-11ea-968e-a0aa8e31dfaa.png)

This actually happens to ALL pointmass maze environments.

**Comment by justinjfu** [comment]
It seems like this is a just cosmetic issue that happens the first time you call render. If you call render in a loop, the first image looks like this and the subsequent images look fine. 

I wasn't able to fix this by setting the target marker position on the first render, so I'm not sure if there is an easy fix. If it's causing other problems please re-open this issue.

**Comment by dh2shin** [comment]
Was this issue ever resolved?

**Comment by dh2shin** [comment]
Nvm I was having trouble with showing the correct position for the red marker, and calling set_marker() helped!
