### ISSUE TITLE
AttributeError: module 'd4rl' has no attribute 'flow'

### ISSUE THREAD

**Issue by wingsweihua** [rail-berkeley/d4rl#39]
https://github.com/rail-berkeley/d4rl/blob/19ff42dfca15a7ecef38c380711da5164a86e26f/d4rl/flow/__init__.py#L26

This causes circular references, maybe should be
`from d4rl.flow import traffic_light_grid as traffic_light_grid`

`from d4rl.flow import merge as merge`

`from d4rl.flow import bottleneck as bottleneck`

**Comment by justinjfu** [comment]
Updated!
