### ISSUE TITLE
Episode information

### ISSUE THREAD

**Issue by shlee94** [rail-berkeley/d4rl#40]
Hello, could you help me figure out how to segment the dataset into trajectories/episodes?
For example, for the halfcheetah datasets, there are no terminal states included, so I assumed first 1000 datapoints correspond to the first episode, the next 1000 the second episode, etc.

The `qlearning_dataset` function from 
https://github.com/rail-berkeley/d4rl/blob/19ff42dfca15a7ecef38c380711da5164a86e26f/d4rl/__init__.py#L38
seems to support my guess. 

But then when I look into the observations more closely, I get, for example for the halfcheetah-medium-v0 environment,
`
print(obs[9000])
`
`
array([-0.03586214, -0.11854211, -0.5709649 ,  0.59237313,  0.25799525,
        0.24009612,  0.04685834, -0.180547  ,  3.6944256 ,  1.2065067 ,
       -1.4099166 ,  1.4494822 , -6.9591885 , 15.26705   ,  3.7576292 ,
        7.2117867 , -9.449336  ], dtype=float32)
`
Or
`
print(obs[10000])
`
`
array([ -0.09099437,   0.11028791,   0.32212004,  -0.32907683,
         0.66518635,  -0.03972699,   0.13382532,  -0.56899893,
         6.4752765 ,   0.26289114,  -2.9174874 ,  19.897604  ,
       -20.984861  ,   4.177299  ,  20.101353  ,  -6.1993895 ,
         1.4919064 ], dtype=float32)
`

These do not seem right for initial observations. AFAIK, initial observation for halfcheetah is a concat of qpos[1:] and qvel, which, upon reset, are small uniform noise around 0 and standard gaussian noise around 0, respectively. 

Any help would be greatly appreciated. Thanks!

**Comment by justinjfu** [comment]
The trajectories are length 999, so obs[998], obs[1997], obs[2996], etc. should be the starting states for cheetah.

We're considering updating the environments with done flags for the MuJoCo tasks, so I'll keep this issue open for now.

**Comment by justinjfu** [comment]
We've added an extra "timeouts" field you can access using the get_datasets() method which should indicate when episodes end due to hitting the max episode length. The 'terminals' field indicates an episode ending due to a termination condition (such as the Walker2D falling over).

We're keeping these fields separate because some Q-learning methods don't use done=True for timesteps ending due to episode length.
