### ISSUE TITLE
Which env version for Mujoco tasks?

### ISSUE THREAD

**Issue by zhan0903** [rail-berkeley/d4rl#45]
Hi, which Mujoco env version is used to generate the offline data, e.g., Hopper-v1 or Hopper-v3? And how to evaluate the agent's performance after training? By testing the agent in an online way, i.e., running it in the env? Thank you.

**Comment by justinjfu** [comment]
They correspond to the v2 envs (i.e. Hopper-v2). And yes, we recommend evaluating the agent in the online way by running them in the env. We are currently working on some off-policy evaluation benchmarks but that is still in progress.
