### ISSUE TITLE
Clarification about Training and Evaluation Task Split

### ISSUE THREAD

**Issue by rasoolfa** [rail-berkeley/d4rl#46]
Hi,

Thanks for sharing this repository. It is great
I'd like to ask about "Training and Evaluation Task Split" in Appendix D and how results are reported in Tables 1 and 3. I am a bit confused how those have been done.
For simplicity, let's assume method _A_ and Maze2D are being used, which of the followings is correct description of what have been done in this paper:

1. _A_ is trained on "maze2d-umaze-v1". Then the leaned model is used to report results on "maze2d-eval-umaze-v1"? In other words, maze2d-eval-umaze-v1 is not used for training and only used to report results?

2. _A's_ hyperparameters are tuned on "maze2d-umaze-v1". Then, _A_ is trained with those hyperparameters and evaluated on "maze2d-eval-umaze-v1"? In other words, maze2d-eval-umaze-v1 is used for both training and evaluation?

3. Or any other scenario?

Thanks for your help.

**Comment by justinjfu** [comment]
Hi, 

We intended the train/eval split to be done according to scenario #2. Although, for the results in the paper we did minimal hyperparameter tuning across the tasks, so with more precise tuning you should be able to exceed the reported numbers.

**Comment by rasoolfa** [comment]
Thanks for your clarification as current text and results in Tables (1 and 3) give an impression that scenario 1 was used.

**Comment by rasoolfa** [comment]
And forgot to mention that it seems Training and Evaluation pairs in **Table 4** are not correct especially for Adroit and Gym, for instance:
**pen-human**(train) vs **hammer-human**(evaluation) 
**halfcheetah-random**(train) vs  **hopper-random**(evaluation)
