### ISSUE TITLE
Computing normalized score

### ISSUE THREAD

**Issue by rasoolfa** [rail-berkeley/d4rl#48]
Hi,

Thanks again for this repository and data. 
I was wondering are **REF_MIN_SCORE** and **REF_MAX_SCORE** ([here](https://github.com/rail-berkeley/d4rl/blob/master/d4rl/infos.py)) used in score normalization described in  section 5.1?
`normalized_score  = 100* (score - REF_MIN_SCORE) / (REF_MAX_SCORE - REF_MIN_SCORE )`

where
```
REF_MIN_SCORE == random_score
REF_MAX_SCORE == expert_score 
```
If not would you please provide **random_score** and **expert score** [section 5.1 in the paper] to make comparison correct ? otherwise, it would be very hard to do correct and fair comparison.

Thanks for your help.

**Comment by wjaskowski** [comment]
I have been also interested in this issue. Why did you close it? Was it somehow resolved?

**Comment by ezhang7423** [comment]
Hi, you can use these two functions:
https://github.com/Farama-Foundation/D4RL/blob/5ef61940a5cbee3146d5de6fab06351e41553788/d4rl/offline_env.py#L71

https://github.com/Farama-Foundation/D4RL/blob/5ef61940a5cbee3146d5de6fab06351e41553788/d4rl/ope.py#L40

**Comment by ezhang7423** [comment]
From these functions, we can see that the `REF_MIN_SCORE` and `REF_MAX_SCORE` are indeed the **random_score** and **expert_score**, respectively.
