### ISSUE TITLE
BRAC dependencies versions seem to be incorrect.

### ISSUE THREAD

**Issue by fuyw** [rail-berkeley/d4rl#50]
I failed to run `train_brac.py` with the given `requirements.txt`. And I find the following dependencies versions work fine:

```
tensorflow==1.15.0
tensorflow-probability==0.8.0rc0
tf-agents==0.3.0
```

Previous `tensorflow==1.14.0` will cause `module 'tensorflow' has no attribute 'TypeSpec'`, and `tensorflow-probability==0.7.0rc0` will cause `TypeError: Tensor is unhashable if Tensor equality is enabled. `

**Comment by justinjfu** [comment]
Thanks! This has been incorporated into a separate evaluations repository at: https://github.com/rail-berkeley/d4rl_evaluations
