### ISSUE TITLE
random-expert dataset?

### ISSUE THREAD

**Issue by vermouth1992** [rail-berkeley/d4rl#52]
Does the random-expert dataset used in CQL paper publish for Hopper, Walke2d and Halfcheetah? Thanks!

**Comment by zhihanyang2022** [comment]
Hi @vermouth1992 , I believe this dataset is not here. But you can definitely try to generate it yourself.

**Comment by vermouth1992** [comment]
That's true. I just want to confirm whether it is generated by simply combining the expert and the random datasets. We have to make sure that they are identical for fair comparison.

**Comment by zhihanyang2022** [comment]
@vermouth1992 I think that's how the authors are doing it: see https://github.com/rail-berkeley/d4rl/issues/19. I hope this helps. On the other hand, I hope the authors @justinjfu add a note on this in the README. By personal experience, I find this way of doing very problematic when coupled with their BCQ implementation in `d4rl_evaluations` repo. In particular, the buffer for BCQ takes the last 1 million transitions from the dataset, which means that, for medium-expert, it ends up only taking the expert data.
