### ISSUE TITLE
Datasets broken after update

### ISSUE THREAD

**Issue by Mr-Pepe** [rail-berkeley/d4rl#64]
Ant maze and maze2d datasets have different numbers of samples for observations/actions/... after pulling the newest version.
@justinjfu Did you break something with your update yesterday?

**Comment by Mr-Pepe** [comment]
The same goes for half cheetah datasets and I guess all locomotion tasks. The mapping between the observations/actions/rewards is broken, so that I can not train a model on the datasets. Resetting d4rl to before the last commits brings everything back to a working state, at least for the locomotion tasks. However, datasets can only be downloaded with the current version, because the URLs changed, which leads to an annoying back and forth between versions.

From my point of view the benchmark in its current state is useless at best and harmful for people that get the current version, because they won't be able to get anything working on the datasets. Of course there might be a problem in my setup, but without any kind of reaction to the issues posted in this repo it's hard to go forward.

**Comment by Yizhao111** [comment]
I get the same problem. At least the shape of halfcheetah is not correct. But the shape of walker2d looks correct.

**Comment by Mr-Pepe** [comment]
Looking at maze2d-umaze-v1, I get 999,999 observations and 987,540 actions.
The difference is 12,459 which is the number of zero observations I mentioned in #65 .

The same goes for halfcheetah-random-v0 with 999,999 observations, 998,999 actions and 1,000 zero observations. I seems that zero observations get inserted into the dataset during loading.

**Comment by justinjfu** [comment]
This should be fixed by #69
