### ISSUE TITLE
Data Coverage in UMaze Env

### ISSUE THREAD

**Issue by kpertsch** [rail-berkeley/d4rl#7]
I visualized the state coverage of the provided data in the 2D maze environments. For the small UMaze environment the downloadable dataset seems to have a skewed data distribution where the agent never fully explores one of the sides:
![image](https://user-images.githubusercontent.com/15955682/80410927-308d9d00-8880-11ea-9e3c-3ec14fe55cc2.png)
The right shows a scatter plot of all positions in the downloaded dataset. Was there a bug in data generation or is this intended? (the data that is used to generate the GIF on the website does not seem to have this issue)

The other two maze environments seem to have full coverage of the maze:
![image](https://user-images.githubusercontent.com/15955682/80410593-b0ffce00-887f-11ea-8bd0-1891db0d42f3.png)

I slightly modified the `visualized_dataset.py` script for these plots:
```
import argparse
import d4rl
import gym


if __name__ == "__main__":
    parser = argparse.ArgumentParser()
    parser.add_argument('--env_name', type=str, default='maze2d-umaze-v0')
    args = parser.parse_args()

    env = gym.make(args.env_name)
    
    dataset = env.get_dataset()
    if 'infos/qpos' not in dataset:
        raise ValueError('Only MuJoCo-based environments can be visualized')
    qpos = dataset['infos/qpos']
    qvel = dataset['infos/qvel']
    rewards = dataset['rewards']
    actions = dataset['actions']

    import matplotlib.pyplot as plt
    plt.scatter(qpos[:, 0], qpos[:, 1])
    plt.axis('equal')
    plt.show()
```

**Comment by justinjfu** [comment]
Looks like the wrong dataset got uploaded - this should be fixed! Delete the cached copy in ~/.d4rl/datasets and you can download a fresh copy.
