### ISSUE TITLE
import error: free(): invalid pointer

### ISSUE THREAD

**Issue by zhan0903** [rail-berkeley/d4rl#70]
When I import d4rl, there was an error:
`Warning: Flow failed to import. Set the environment variable D4RL_SUPPRESS_IMPORT_ERROR=1 to suppress this message. 
No module named 'flow.envs'
free():invalid pointer
Aborted (core dumped)
`
Any suggestions? Thank you.

**Comment by MouseHu** [comment]
For those who also meet this error:
I meet this error too and I find this is because I mis-installed the packages carla and flow through pip, which is actually not the packages we need, but packages with the same name.
I solve this error by running
`pip uninstall flow`
`pip uninstall carla`

**Comment by HenryZhang-git** [comment]
> 

Hi,I also meet this error,but when i use the method which you tell us,it back to me:
`(py37) D:\PyProject\test_d4rl>pip uninstall flow
WARNING: Skipping flow as it is not installed.

(py37) D:\PyProject\test_d4rl>pip uninstall carla
WARNING: Skipping carla as it is not installed.`
I don't konw what should I do.
