### ISSUE TITLE
Question about the normalization of results and the benchmarked CQL performance in Table 2 (ICLR submission)

### ISSUE THREAD

**Issue by Yizhao111** [rail-berkeley/d4rl#72]
Hi,

Thanks so much for your work. I have a question about the normalization of results. Specifically, e.g., in the Gym domain, each result is normalized according to the expert-policy (sac) and random-policy. But which number should we refer to?  On the Wiki/"Off policy evaluation" page, there is a form that includes the expert-policy and random-policy, should we refer these? Also, the results of the expert-policy are different from the SAC results in Table3 (ICLR), so which one should we use? 

And I noticed that in Table 2 and 3 (ICLR), the result of CQL-'hopper-medium' seems not aligned, could you please confirm this (maybe also the CQL-'walker2d-medium')? 

Thanks.

**Comment by zhihanyang2022** [comment]
I think this is indeed an issue about reproducibility, i.e., while the CQL algorithm is fully available in Kumar's Github repo, **the random and expert scores are not made available**. 

At this moment, I think you can refer to the un-normalized / raw scores at the end of D4RL's ICLR submission. However, that table (1) does not include scores for CQL(rho) and (2) does not include scores for expert datasets and etc.

**Comment by zhihanyang2022** [comment]
Actually, thanks to Justin Fu's email reply, we can find the random and expert scores here: https://github.com/rail-berkeley/d4rl/blob/master/d4rl/infos.py.

**Comment by Yizhao111** [comment]
Thanks a lot! I will close this issue.
