### ISSUE TITLE
logging policy propensities available?

### ISSUE THREAD

**Issue by kaiwenw** [rail-berkeley/d4rl#74]
is it possible to access the propensities (pi(a|s) for each transition s,a,r) of the logging policy while making the dataset? this would be useful for algorithms that aren't policy agnostic.

**Comment by justinjfu** [comment]
Thanks for the suggestion! This is currently implemented for a subset of the tasks listed here: https://github.com/rail-berkeley/d4rl/wiki/Tasks

In summary, there is an `infos/action_log_probs` field stored in the dataset for the expert Adroit datasets (-v1 tasks only), and the expert+medium MuJoCo Gym datasets (also -v1). 

We don't have propensities available for the other datasets as they were not generated from a probabilistic policy. For example, the maze datasets were generated by following waypoints, and several tasks use human demonstrations or a hand-coded controller.
