### ISSUE TITLE
Datasets incorrect? Expert data rewards seem worse than medium data

### ISSUE THREAD

**Issue by aravindr93** [rail-berkeley/d4rl#76]
Hello, I'm noticing that the expert data is of very low quality as shown below. Could the datasets be incorrect, or am I processing the data incorrectly? Thanks!

```
import gym
import d4rl
import numpy as np

e_medium = gym.make('hopper-medium-v1'); data_medium = e_medium.get_dataset()
e_expert = gym.make('hopper-expert-v1'); data_expert = e_expert.get_dataset()

print(np.mean(data_medium['rewards']), np.mean(data_expert['rewards']))
```
Results in the following output which seems incorrect to me.
```
3.47  1.50
```

**Comment by aravindr93** [comment]
Amortizing over a trajectory length of 1000 (standard for gym), it seems like the medium dataset is collected with a policy getting a score of approx 3470 which is very close to optimal. On the other hand, the expert dataset is collected with a policy of score 1500, which seems closer to a medium sub-optimal policy.

I'm guessing the datasets have been named incorrectly when uploading?

**Comment by justinjfu** [comment]
Thanks - I swapped the two datasets. Clean the downloaded datasets (`rm ~/.d4rl/datasets/hopper*v1.hdf5') and you can download them again.

**Comment by zhihanyang2022** [comment]
I have a similar question about hopper_medium_replay:

```
env = gym.make('hopper-random-v1')
dataset = env.get_dataset()
print(np.mean(dataset['rewards']))  # 0.8286486

env = gym.make('hopper-medium-v1')
dataset = env.get_dataset()
print(np.mean(dataset['rewards']))  # 1.5018191

env = gym.make('hopper-expert-v1')
dataset = env.get_dataset()
print(np.mean(dataset['rewards']))  # 3.466414

env = gym.make('hopper-medium-replay-v1')
dataset = env.get_dataset()
print(np.mean(dataset['rewards']))  # 3.0534504202260146
```

I don't think it makes sense for medium replay to have a higher per-step reward than medium.
