### ISSUE TITLE
Easy way to compute maze coverage

### ISSUE THREAD

**Issue by josuenassar** [rail-berkeley/d4rl#78]
Hi, 

For the maze environments, I'm interested in converting an agent's (x, y)-position into what cell of the maze they are located so I can easily compute the percentage of the maze the agent has explored. 

In the code, I saw that each maze environment has its own representation i.e.:
```
U_MAZE = \
        "#####\\"+\
        "#GOO#\\"+\
        "###O#\\"+\
        "#OOO#\\"+\
        "#####"
```
but what I haven't been able to find are the centers of each of the open positions and their corresponding height and width (for both the point maze and ant maze).

Thanks!

**Comment by Mr-Pepe** [comment]
There is a collision detection in maze_env.py.

```Python
x, y = pos
structure = self._maze_map
size_scaling = self._maze_size_scaling
for i in range(len(structure)):
  for j in range(len(structure[0])):
    if structure[i][j] == 1:
      minx = j * size_scaling - size_scaling * 0.5 - self._init_torso_x
      maxx = j * size_scaling + size_scaling * 0.5 - self._init_torso_x
      miny = i * size_scaling - size_scaling * 0.5 - self._init_torso_y
      maxy = i * size_scaling + size_scaling * 0.5 - self._init_torso_y
      if minx <= x <= maxx and miny <= y <= maxy:
        return True
return False

```

The scaling factor is 4 (defined [here](https://github.com/rail-berkeley/d4rl/blob/master/d4rl/locomotion/__init__.py)). 

I'm not sure about the point maze.

**Comment by josuenassar** [comment]
Thanks! Given this, for antmaze one way to compute it is given the (x, y) coordinate add 2, divide by 4 and apply to the floor function. One can then use this to index into the array representation for the maze.

For point maze, you subtract by .3 and then apply the floor function (I found this out through trial and error :) )
Thanks again for the quick response!
