### ISSUE TITLE
infos/qpos & infos/qvel in MuJoCo Gym are incorrect.

### ISSUE THREAD

**Issue by j0rd1smit** [rail-berkeley/d4rl#84]
For multiple MuJoCo gym-based tasks are the infos/qpos & infos/qvel incorrect. There are only two unique values in the entire array.
```
env = gym.make("halfcheetah-medium-v1")
qpos = dataset['infos/qpos']
qvel = dataset['infos/qvel']

print(len(np.unique(qpos, axis=0))) # prints 2
print(len(np.unique(qvel, axis=0))) # prints 2
```

So far this following datasets:
- halfcheetah-medium-v1
- halfcheetah-expert-v1
- halfcheetah-medium-replay-v1
- hopper-medium-v1

Note: I have **not** tried the other yet. However, so far it appears to be true for everyone I tried.
Note: the infos/qpos & infos/qvel are correct for Maze2D & AntMaze

**Comment by justinjfu** [comment]
Thanks for raising this issue. I'll look into this and I'm considering regenerating the datasets after collecting the current set of bugfixes.
