### ISSUE TITLE
Error: "TimeLimit" object has no attribute 'get_dataset'

### ISSUE THREAD

**Issue by Yizhao111** [rail-berkeley/d4rl#87]
Hi,

When run `env.get_dataset()`, I met the error: "TimeLimit" object has no attribute 'get_dataset'. 
- I can successfully import `d4rl`, and `gym.make`, `env.reset()`, and `env.step` with env, but I can't run `env.get_dataset()`. 
- I use the latested d4rl, the mujoco-py: 2.0.2.13 and mujoco2.0. 
- Use `env=env.unwrapped` can solve this.

Best,
Yi

**Comment by justinjfu** [comment]
This might be caused by your Gym version. Could you try updating to the most recent version of gym and try again?

**Comment by Yizhao111** [comment]
Yes, you're correct. Updating to the latest gym version (0.18.0) solves this. My previous gym version is 0.12.0. Thanks a lot!

**Comment by HYDesmondLiu** [comment]
I am using gym 0.18.0 but still there is no `get_dataset()`

**Comment by yuanyaaa** [comment]
The load code maybe like "env = gym.make("Hopper-random")" rather than "env = gym.make("Hopper-v2")". 
This is work for me!
