### ISSUE TITLE
CustomMDPPathCollector

### ISSUE THREAD

**Issue by Jiankai-Sun** [rail-berkeley/d4rl#9]
Firstly, thank you.

After `python antmaze_bear.py`,
![image](https://user-images.githubusercontent.com/25477396/80577094-e1d73300-8a38-11ea-941a-1f3c57a1e539.png)

It seems that rlkit (already installed the latest version) doesn't contain `CustomMDPPathCollector`. Is this your custom class?

**Comment by ruizhaogit** [comment]
Thank you for the great work! @justinjfu  
I also ran into the same error @Jiankai-Sun . It seems that "VAEPolicy" is also missing. Which "rlkit" fork are you using @justinjfu or is there an "rlkit" fork that has not been released yet?

**Comment by aviralkumar2907** [comment]
Thanks for pointing out this issue. 

We will release the rlkit fork we built off of soon, meanwhile, we have added support for D4RL in the BEAR repo, which can be found here: https://github.com/aviralkumar2907/BEAR, and that should run without any issues.

**Comment by ruizhaogit** [comment]
Couldn't reproduce the results reported in D4RL, see post here https://github.com/aviralkumar2907/BEAR/issues/5 @aviralkumar2907 @justinjfu
