### ISSUE TITLE
Poses of microwave and hingecabinet

### ISSUE THREAD

**Issue by clemense** [rail-berkeley/d4rl#99]
Hi,
I'm converting the Mujoco kitchen scene to a different format. Unfortunately, the result doesn't look like what is shown in the paper/on the website:  (see poses of the "microwave" and "hingecabinet")
![image](https://user-images.githubusercontent.com/1800546/119240091-77d97200-bb02-11eb-86e5-1c111ef41336.png)
![Screenshot from 2021-05-22 14-15-32](https://user-images.githubusercontent.com/1800546/119240965-406dc400-bb08-11eb-9bd2-09b2830ce54f.png)

Where can I find the true transformations for the microwave and hingecabinet?
Thanks!

**Comment by justinjfu** [comment]
Hi,

You could maybe take a look at this file in the adept_envs repo, which contains all of the transformations for each of the components: https://github.com/google-research/relay-policy-learning/blob/master/adept_models/kitchen/kitchen.xml

**Comment by clemense** [comment]
Thanks! Yes, I used that file when converting to URDF. But these transforms do not match the image (seen above) for the microwave and hingecabinet (actually also the the sliding cabinet, but this translation mismatch is smaller).

Another dummy check you can do: The microwave is clearly not aligned with any world axis, i.e. its orientation in euler angles can't be a multiple of pi/2. But there is no such number in the xml files (at least I can't find any). Where are the correct transforms for these objects defined?

**Comment by justinjfu** [comment]
Perhaps you could re-raise this issue in the adept_envs repo? (https://github.com/google-research/relay-policy-learning/issues) I'm personally not familiar with the details of the environment, so maybe the developers of it could help you more.

Doing some more searching, it looks like there's another location where the microwave is defined here which is not axis-aligned: https://github.com/google-research/relay-policy-learning/blob/master/adept_envs/adept_envs/franka/assets/franka_kitchen_jntpos_act_ab.xml#L78
